# Site settings
title: Dawa Sherpa Guiding
description: 'Site for my sherpa guiding company.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://matt-cairnduff-deliveroo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/_images/Roo.svg"
logo-icon: "/_images/Roo.svg"
logo-icon-SEO: "/_images/deliveroo_logo.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/_images/Roo.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Dawa Tshering # add your name
author-pic: Myself_Neon_grey.jpg
about-author: Guide with over 11 years experience in mountaineering, ice climbing, and trekking in high mountain areas.

# Contact links
email: Email address here # Add your Email address
phone: +977 986 1509985 
twitter: Twitter here
facebook: Facebook here

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200


# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
