theme: jekyll-theme-modernist
title: Nepal Trekking Homepage
description: This page contains details about ...

---
  defaults:
    # _docs
    - scope:
        path: ""
        type: main
      values:
        sidebar:
          nav: "main"
  ---        
