theme: jekyll-theme-minimal
title: Nepal Trekking Homepage
description: This page contains details about ...
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
